[phases.setup]
nixPkgs = ['php', 'php82Packages.composer', 'php82Extensions.pdo_sqlite']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'chmod -R 775 database',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
  'php artisan migrate --force'
]

[phases.start]
cmds = ['php artisan serve --host=0.0.0.0 --port=$PORT']
